language: node_js
node_js:
  - '12'
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: IYAIi+K69g4uWMNiS59ifiNKzWCRFJ1AtkbUNN0n0+XyZt5LW/oghIQeCi57/X16CwgZu4M+dQZ8SDE3dxQw65Gaw4cNXpx8gA0GKDV3jrydB9qT7/qpwoAGGvsbjzs/Y+TEOMCrh/p34o4G199btq0ySOnbg3RMoStNskgRn6Vp0DtB0+Q2CcMS0IsVanEJysbD0ojcSJZ2+CKKkWtP9EXdzYfOtZ32COQobCAgW3sxk0ywN8IwCIok7l+HqBbiH0FvE/xFxiYklYK2z91fz/KP6fctN6Sa4WJjQinnOaQIZSdKGLvXX3ckPC2cWDPOPK7dfQ9qRY7poMcrqVka13hZLv7RzucEPzX7b1A1z4EG8gh4uC+SXomUg6aiZjl/cmekTucBB1Z0CdXqXM7lOamGM29TAy+6EWiqWQv8IjuwLRy1bXR8arAC203OTiapf9A++ecyl7EK8Ar3LoCyHeTvzqm5lVD6ZlSaPOQGKds8/YIU5vBciDDwq+AtgKAh1iIos6Xhn5TAGT5avpK7EH41PpYk+fOE8y/953S1Vm9FU/Qqf6fwsNaZS2rffCOQ09SMeoaJVvPvE7Jaq5eFgVzup5GmH0tWQtqil6w062dmvmuq3dGGAQUS/MgDSyzFSRD0jYdyNbJv4MkD0Ef5GBD/WTQHSc47RQKwlHHmkAc=
  app: banking-heroku
notifications:
  email:
    on_failure: change
    on_success: change
